language: r
cache:
  - $HOME/.ccache
  - packages
cran: https://cloud.r-project.org
env:
  global:
    - CRAN_REPO=https://cloud.r-project.org
jobs:
  include:
  # - os: linux
  #   dist: xenial
  #   r: oldrel
  #   addons:
  #     apt:
  #       sources:
  #       - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
  #       packages:
  #       - ccache
  #       - gdal-bin
  #       - libgdal-dev
  #       - libgdal1-dev
  #       - libgeos-dev
  #       - libgit2-dev
  #       - libmagick++-dev
  #       - libnlopt-dev
  #       - libproj-dev
  #       - libudunits2-dev
  #   services:
  #     - xvfb
  #   before_install:
  #     - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  #     - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
  #   r_binary_packages:
  #     - BH
  #     - dplyr
  #     - ggplot2
  #     - igraph
  #     - RSQlite
  #     - stringi
  #   r_packages:
  #     - rgdal
  #     - rgeos
  - os: linux
    dist: xenial
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - ccache
        - gdal-bin
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libgit2-dev
        - libmagick++-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
    services:
      - xvfb
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
    r_binary_packages:
      - BH
      - dplyr
      - ggplot2
      - igraph
      - RSQlite
      - stringi
    r_packages:
      - covr
      - devtools
      - rgdal
      - rgeos
    r_github_packages:
      - jimhester/lintr
    after_success:
      - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
      - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - ccache
        - gdal-bin
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libgit2-dev
        - libmagick++-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - libxml2-dev
    services:
      - xvfb
    r: devel
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
    r_binary_packages:
      - BH
      - dplyr
      - ggplot2
      - igraph
      - RSQlite
      - stringi
    r_packages:
      - devtools
      - rgdal
      - rgeos
      - XML
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - imagemagick@6
        - libgit2
        - libxml2
        - udunits
        update: true
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_install:
      - Rscript -e "install.packages(c('rgdal', 'rgeos', 'XML'), type = 'source')"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
